# Generated by Django 5.0.6 on 2024-06-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='engine',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
